### PR TITLE
change Ingress to use external provided buffer

### PR DESCRIPTION
**Pull request by dragonnn**
One place where stack usage can blow up when using atat with a huge Ingress buffer is in Ingress with uses an internal buffer and is copied in embassy to an external task. 
This does change Ingress struct to take an external buffer.
I am not sure if this is the best way to handle it, it has the downside to force to use static_cell on std (or some other way of making a static buf, is they something for that in std?).
I also removed the singleton macro from examples and made use directly off make_static from static_cell. As far I know both do the same anyway and both do need nightly.

### CODE REVIEW

**Comment by rmja** [comment]
If we do this, then we should remove the INGRESS_BUF_SIZE const generic completely? That would be awesome. If we do not do that, then this does not really change anything, does it? Usually the Buffers struct is static anyway.

**Comment by dragonnn** [comment]
It does change, the point of this change was changing this line:
https://github.com/BlackbirdHQ/atat/pull/189/files#diff-a7fda104c938eae3841924f20450d6149a8e78039ea8f97b6a5b2b84373fba88L112
Before that change Ingress struct owned it's buffer `buf: [0; INGRESS_BUF_SIZE],` so when Ingress was moved to another task to run in background this made a bunch of memcpy blowing up the stack.
INGRESS_BUF_SIZE is also used by ResponsePublisher so I don't think it can be removed?
And I suspect having ResponsePublisher and Ingress use different size buffers might be not desired?

**Comment by MathiasKoch** [comment]
I tend to agree with @rmja.
I am not sure if I see the value in having `INGRESS_BUF_SIZE` with this change?

**Comment by rmja** [comment]
I wonder if this is still needed now when Buffers are removed, as Ingress is not moved to a different task anymore - it it simply created "over there".

**Comment by dragonnn** [comment]
I think it still will be more consistent with https://github.com/BlackbirdHQ/atat/pull/189 since on it now AtClient does take an external buff, that would make the consistent and avoids having hidden big buffers inside atat structs. And with the use of unsafe allows an user to reuse the buffer for something else when for example the modem is shutdown.

**Comment by dragonnn** [comment]
Hi! Sorry for the delay, I rebased my PR on master. I still think this is useful and allows all sort of shenanigans like providing a buffer from heap memory, putting it even somewhere else in the MCU memory when linking etc.
I could change Ingress to store `buf: &mut [u8],` instead of using the generic parameter but that parameter still would be used by `res_slot: &'a ResponseSlot<INGRESS_BUF_SIZE>,` so not sure if it is worth it and will not lead to other issues when decoupling them (didn't try yet).

**Comment by rmja** [comment]
I think you should change to  buf: &mut [u8], and rename the generic parameter to RES_BUF_SIZE. And where appropriate, make sure that the res_slot is large enough. There is actually a use case for having the res_slot smaller than the ingress buffer for when the large downloads are actually happening through urc's.

**Comment by dragonnn** [comment]
Done, I think res_slot is checked and logged in each place when stuff is put into it?
Did you have anything more in mind then already is in place?

**Comment by rmja** [comment]
This looks good to me, thanks!

**Review by MathiasKoch — APPROVED** [review]
Looks great to me :+1: 
Thank you!

**Pull request merged**
