### PR TITLE
update deps, use fugit_timer::Timer instead of Clocks

### PR DESCRIPTION
**Pull request by burrbull**
I've moved `Clocks` in separate crate as it's too hard to implement it in HALs during this part of `atat`.
In other side it can't be a part of `embedded-hal` as `fugit` primitives are only one of possible solutions.

### CODE REVIEW

**Review by MathiasKoch — APPROVED** [review]
Awesome! Thank you for you contribution. Looks good to me :+1:

**Comment by burrbull** [comment]
defmt now use `DEFMT_LOG` env variable for log level
https://defmt.ferrous-systems.com/migration-02-03.html

**Comment by MathiasKoch** [comment]
Yeah, that shouldn't be an issue

**Comment by burrbull** [comment]
Could you rerun CI?

**Comment by MathiasKoch** [comment]
@burrbull Would you mind fixing the minor stuff causing examples to fail? 
I updated the dev dependency to use embedded-hal v1.0.0-alpha.6, so it should be straight forward now

**Comment by burrbull** [comment]
Should be done

**Comment by MathiasKoch** [comment]
Hmm still not completely there.

**Comment by MathiasKoch** [comment]
Just needs an `nb` here now: https://github.com/BlackbirdHQ/atat/pull/113/files#diff-fab342aa22e4a3b3e48e65e6794d8bd39f60872f7381fb7e2cb4bca7d7205891R2

**Comment by burrbull** [comment]
Try again

**Comment by MathiasKoch** [comment]
Thank you very much!

**Pull request merged**
