### PR TITLE
Reduce stack usage

### PR DESCRIPTION
**Pull request by rmja**
This is a proposal to write request to a re-useable buffer instead of allocating the heapless Vec on the stack.
If this is something that we decide to go with, then we should also do something to reuse the same buffer when parsing the response.
Note, there is a todo in `serde_at/src/ser/mod.rs` when compiled without heapless.

### CODE REVIEW

**Comment by MathiasKoch** [comment]
I am not sure if I understand how this saves stack? It makes it easier to be certain you have enough stack available, as you do the allocation up front, but wouldn't you still need the same size, with the limitation that it is much harder to calculate now, as you need to know up from what the serialized size of your biggest command + arguments is throughout the entire program?

**Comment by MathiasKoch** [comment]
@rmja Is this still relevant?

**Comment by rmja** [comment]
Yes, I believe so. This PR also removed 2k of my code size.

**Comment by rmja** [comment]
@dragonnn could you verify that this in fact reduce the stack usage? I known that we still need to handle the stack usage of the response.

**Comment by dragonnn** [comment]
Yes, it does. Helps already a lot, thanks :)

**Comment by rmja** [comment]
@dragonnn awesome! The last few commits depends on https://github.com/embassy-rs/embassy/pull/2328.

**Review by MathiasKoch — APPROVED** [review]

**Comment by MathiasKoch** [comment]
@rmja This looks nice!

Could you fix the CI?

**Comment by rmja** [comment]
Ok, I need some help.
I have updated CI to now also test with `async` feature. For that to compile, I had to remove these two tests: https://github.com/BlackbirdHQ/atat/pull/190/commits/d8ed5aa2037357d77b982bfa5b4b58aa65b51e40

Can anyone help with getting these two tests back?

**Comment by MathiasKoch** [comment]
What is the issue with them? (can't check it out right now)

**Comment by rmja** [comment]
OMG: CI is green! I would really appreciate if the two of you could have a look again!

**Comment by dragonnn** [comment]
Works fine in my project, didn't notice any issue and no changes where need from previous commit I tested.

**Review by MathiasKoch — APPROVED** [review]
Looks great!

Thank you very much for your efforts on this! 
Can't wait to try it out on my own devices. Sadly, I still have a bit of way on migrating blocking code to async before I can fully upgrade.

**Pull request merged**
