### PR TITLE
Fix digest continuation bug

### LINKED ISSUE #140: custom handlers in AtDigester should support returning nom::Err::Incomplete
The current `digest()` method for `AtDigester` looks like this:

https://github.com/BlackbirdHQ/atat/blob/a4608e9020ea8f1cd40e2677ee39d67bae2df699/atat/src/digest.rs#L110-L160

I have a `custom_succes` that handles reading binary data from the modem. For example:

```rust
AtDigester::new()
            .with_custom_success(|buf| {
                let (_reminder, (head, data, tail)) = branch::alt((
                    sequence::tuple((
                        combinator::success(&b""[..]),
                        combinator::success(&b""[..]),
                        bytes::streaming::tag(b"\r\nSHUT OK\r\n"),
                    )),
                    sequence::tuple((
                        bytes::streaming::tag(b"\r\n"),
                        combinator::recognize(sequence::tuple((
                            bytes::streaming::tag(b"+CIPRXGET: 2,"),
                            character::streaming::u8,
                            bytes::streaming::tag(","),
                            combinator::flat_map(character::streaming::u16, |data_len| {
                                combinator::recognize(sequence::tuple((
                                    bytes::streaming::tag(","),
                                    character::streaming::u16,
                                    bytes::streaming::tag("\r\n"),
                                    bytes::streaming::take(data_len),
                                )))
                            }),
                        ))),
                        bytes::streaming::tag(b"\r\nOK\r\n"),
                    )),
                ))(buf)?;

                Ok((data, head.len() + data.len() + tail.len()))
            })
```

The `+CIPRXGET` is basically a header followed by the binary data followed by OK.

It returns `ParseError::Incomplete` until the entire sequence of bytes is received. Currently the digest method does not honor this. It simply continues to the next "possible DigestResult candidate" in `digest()` because the result from the custom success handler is not Ok. Effectively this often finds a prompt "> " in the binary data.

### PR DESCRIPTION
**Pull request by rmja**
The digest should not continue to lower priority cases if the parser returns incomplete.

This fixes #140

### CODE REVIEW

**Comment by MathiasKoch** [comment]
This is a nice catch!

Could you fix the clippy CI, so I can merge it?

**Comment by MathiasKoch** [comment]
It runs with `-- -W clippy::all -W clippy::pedantic -W clippy::nursery -W clippy::cargo` in CI

**Comment by rmja** [comment]
From the CI details I get "Error: Unable to create clippy annotations! Reason: HttpError: Resource not accessible by integration". It seems unrelated to the PR?

**Comment by MathiasKoch** [comment]
I think this is what it fails on:

```
error: this could be rewritten as `let...else`
   --> serde_at/src/de/mod.rs:676:5
    |
676 | /     let from = match x.iter().position(|x| !x.is_ascii_whitespace()) {
677 | |         Some(i) => i,
678 | |         None => return &x[0..0],
679 | |     };
    | |______^ help: consider writing: `let Some(i) = x.iter().position(|x| !x.is_ascii_whitespace()) else { return &x[0..0] };`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_let_else
note: the lint level is defined here
   --> serde_at/src/lib.rs:6:9
    |
6   | #![deny(warnings)]
    |         ^^^^^^^^
    = note: `#[deny(clippy::manual_let_else)]` implied by `#[deny(warnings)]`

```

**Comment by rmja** [comment]
@MathiasKoch it seems happy now:-)

**Pull request merged**
