### PR TITLE
reimplement log-logging feature

### PR DESCRIPTION
**Pull request by fkohlgrueber**
This is a WIP PR to reintroduce the `log-logging` feature flag (as has been discussed in #86 ).

I first looked at the changes from #80 but then decided to introduce a new `LossyStr` type that's wrapping `&[u8]` and implementing formatting as a str (if possible) for both defmt and core::fmt::Debug. This way, there's no need to use feature flags when calling `atat_log` with a byte slice as param.

I haven't fully tested the code yet, but I wanted to open the PR to gather feedback.

Have a great day ;-)

### CODE REVIEW

**Comment by MathiasKoch** [comment]
> but then decided to introduce a new LossyStr type that's wrapping &[u8] and implementing formatting as a str (if possible) for both defmt and core::fmt::Debug

That is an awesome way to do it! Can't believe i haven't though of that!

Looks good at first glance! :+1:

**Comment by fkohlgrueber** [comment]
I'm currently thinking about how the CI scrips should be updated. I've implemented the features such that 
1. no features -> no logging
2. just log-logging -> logging using `log`
3. any defmt-* features, but not log-logging -> logging using `defmt`
4. any defmt-* features and log-logging -> compile error

I think the CI should make sure that the code compiles for 1.-3.
I don't think we need to test that there's a compile error for 4.

Du you agree?

**Comment by MathiasKoch** [comment]
I think your condition checks might be simplified a bit by introducing a `defmt-logging` feature such that:

```toml
[features]
default = ["defmt-default"]

defmt-logging = ["defmt"]
log-logging = ["log"]

defmt-default = ["defmt-logging"]
defmt-error = ["defmt-logging"]
defmt-warn = ["defmt-logging"]
defmt-debug = ["defmt-logging"]
defmt-info = ["defmt-logging"]
```

And then making the derive for `defmt::Format` conditional based on `defmt-logging`?

Furthermore it removes the need for defmt in your dependency graph, if you are only interested in using `log`?

What you think?


Regarding the CI i would agree with points 1, 2 & 3 being most relevant

**Comment by fkohlgrueber** [comment]
> And then making the derive for defmt::Format conditional based on defmt-logging?
> 
> Furthermore it removes the need for defmt in your dependency graph, if you are only interested in using log?

That sounds really beneficial, especially because defmt can cause linker errors when compiled for x86.

Do we really need the `defmt-logging` and `log-logging` features? Simply using `log` and `defmt` should be enough, right? This would also be consistent to the way smoltcp does it, see https://github.com/smoltcp-rs/smoltcp/pull/455.

**Comment by MathiasKoch** [comment]
I don't think a feature and an optional dependency can have the same name? 🤔

**Comment by dbrgn** [comment]
> I don't think a feature and an optional dependency can have the same name? thinking

If the feature flag should simply enable/disable that one optional dependency, then it works. However, it cannot be used to "group" multiple optional dependencies.

**Comment by MathiasKoch** [comment]
Aha, TIL 😊👍

**Comment by dbrgn** [comment]
(Or, in other words: If you have an optional dependency on the crate "foobar", then "foobar" will automatically be a cargo feature, without even defining it. This means that you cannot define your own custom "foobar" flag, since it would conflict.)

**Comment by MathiasKoch** [comment]
Ahh that makes sense :+1: 

I just wasn't aware you could still `#[cfg(feature = ..)]` on optional dependencies.

**Comment by fkohlgrueber** [comment]
I updated the branch:
- `defmt` is now optional (feature "defmt" and implicitly used by "defmt-default" etc.)
- removed the trait bound `E: defmt::Format` from the `Error` enum (if the `defmt` feature isn't set, there's no way to enforce the trait bound. Only requiring it when the feature is used seems odd to me.)
- `log-logging` feature removed (simply use "log" feature)
- updated readme and CI script

I also tested the logging output on x86 (using `log`) and on a blue pill (using `defmt`):

```
# log
[2021-05-16T19:39:52Z DEBUG atat::client] Sending command: ""AT+CIPSTATUS\r\n""

# defmt
     723 DEBUG Sending command: "b"AT+CIPCLOSE\r\n""
└─ atat::client::{{impl}}::send @ /home/felix/tmp/atat/atat/src/helpers.rs:128
```

Seems to work fine. From my side, this looks ready to be integrated now. Can you review the PR please? 

Thanks in advance!

**Review by MathiasKoch — APPROVED** [review]
Looks good to me :+1:

**Pull request merged**
