### PR TITLE
Async client

### PR DESCRIPTION
**Pull request by rmja**
This PR adds an async atat client.
It incurs some major changes to the current project structure, so it should be merged with care.

There are some outstanding issues:
* There is a mode property on Config. Is it deprecated now?
* The version of bbqueue is from a PR with async support
* The timer libs should probably be aligned

### CODE REVIEW

**Review by unizippro — APPROVED** [review]
LGTM

**Comment by MathiasKoch** [comment]
Async is a protected keyword in rust, so the Convention is to use asynch

**Comment by mvniekerk** [comment]
Hi @rmja 
I've pulled in your changes into my fork (https://github.com/mvniekerk/atat/) 

https://github.com/mvniekerk/moko-mkl62ba-embassy/blob/ba9299dce32dc9fff98d0ded83524072fc018d9b/examples/pico-uart/src/main.rs#L87

The safe buffer size guard seems not to be working. Would've been cool if it did though.

**Comment by rmja** [comment]
@mvniekerk 

It turns out that the issue has to do with the way the new is called:


```rust
    static buffers_work: Buffers<Urc, 500, 1010, 10, 1> =
        Buffers::<Urc, 500, 1010, 10, 1>::new();

    static buffers_does_not_work: Buffers<Urc, 500, 1010, 10, 1> =
         Buffers::new();
```

Apparently one needs to be explicit about the turbofish when calling new.

**Comment by rmja** [comment]
Either that, or you need to define `#![feature(generic_const_exprs)]` in `main.rs`. If you do that, then the second one will also work.

**Comment by mvniekerk** [comment]
I've tested adding the params, it worked. Thanks @rmja

**Comment by MathiasKoch** [comment]
- CI is green ✅
- README has been updated ✅
- Examples are compiling and working ✅ (Might not be the best examples, but better than before)

@rmja Ready to merge this, so we can add a followup PR with the pubsub URC handling, and code-size optimizations?

**Review by MathiasKoch — APPROVED** [review]

**Comment by rmja** [comment]
Really nice. Yes!

**Comment by MathiasKoch** [comment]
Will you rebase, and open the followup PR? :)

**Pull request merged**
