### PR TITLE
Add ability for custom computation of response timeout instant

### PR DESCRIPTION
**Pull request by rmja**

### CODE REVIEW

**Comment by MathiasKoch** [comment]
I think overall this should be okay, considering it's not a lot of code, and it allows people to solve an actual problem.

That said, I would like a simple usage example, perhaps also a unit test if possible? Mostly because I have a hunch this is one of those "features" that are bound to break over time if not regularly tested, due to the few people using it.

**Comment by rmja** [comment]
@MathiasKoch Sorry for the lack of a response here. I have updated the pr with tests for both the blocking and async client. I think the tests cover the intended behavior.

**Comment by rmja** [comment]
The CI error is due to this https://github.com/rust-lang/rust/issues/113152.
Can we force a cargo update?

**Comment by MathiasKoch** [comment]
@rmja  Looks good. Could you rebase to fix the conflict, and allow the CI to be green?

**Comment by rmja** [comment]
All green:)

**Pull request merged**
