### PR TITLE
update heapless

### PR DESCRIPTION
**Pull request by tarfu**

### CODE REVIEW

**Comment by MathiasKoch** [comment]
Thanks!

**Comment by rmja** [comment]
This now includes two versions of heapless because `heapless-bytes` has not yet updated to 0.8, see https://github.com/ycrypto/heapless-bytes/pull/2. Lets hope that it gets released soon.

**Comment by tarfu** [comment]
Yes, I hope for a sign of live in the heapless-bytes repo, I really don't want to fork it.

**Comment by tarfu** [comment]
@rmja @MathiasKoch  Maybe basing the dependency on https://github.com/ycrypto/heapless-bytes/pull/3 is the right way to go, or forking it. Basically like no-std-net in the ublox-cellular crate.

**Pull request merged**
