### PR TITLE
Add reattempt on parse err flag to AtatCmd

### PR DESCRIPTION
**Pull request by dragonnn**
This can be useful when modem does throw out some not need information at initialization. For example my after unlocking the SIM card PIN throws out after short delay `+CPIN: READY\r\n\r\n+QUSIM: 1\r\n\r\n+QIND: SMS DONE\r\n`.
That breaks the next command I run, if I just use the reattempt_on_parse_err flag that command is repeated and works fine.
I could add all the stuff it does output after +CPIN to Urc but I don't need that in this case, would only clatter my enum.
I think this can be also useful for any transmissions errors on the serial if someone has an unstable connection.

### CODE REVIEW

**Review by MathiasKoch — APPROVED** [review]
This looks like a reasonable addition to me :+1: 

Is there any reason not to have this default enabled?

**Comment by dragonnn** [comment]
> Is there any reason not to have this default enabled?

They only reason I made it disable by default is that it isn't present currently , so when an user updates the behavior doesn't change if the code stays the same. If you are fine with making that default I am all for it too, for most commands I would prefer to have it enabled in my case.

**Comment by MathiasKoch** [comment]
I think for all the cases I can think of, it would probably make sense to have it enabled.
What would the behavior be if it keeps failing parsing?

**Comment by MathiasKoch** [comment]
sounds reasonable :+1:

**Pull request merged**
