### PR TITLE
Fixed handling multiline responses

### PR DESCRIPTION
**Pull request by MathiasKoch**
* Fixed handling multiline responses, and added a test for it. 
* Bumb `get_line()` length from `U64` to `U128`.
* Change `parse_at` to `digest`

Fixes https://github.com/dbrgn/espresso/issues/1

### CODE REVIEW

**Comment by dbrgn** [comment]
Awesome, this fixes the `AT+GMR` multi-line response issue!

```
Starting (dev=/dev/ttyUSB0, baud=115200)...
Sending command GetFirmwareVersion
[2020-03-14T17:23:31Z DEBUG atat::client] Sending command: "AT+GMR\r\n"
[2020-03-14T17:23:32Z TRACE atat::ingress_manager] Ingress: Receiving 32 bytes
[2020-03-14T17:23:32Z TRACE atat::ingress_manager] Ingress: Parsing / Idle / "AT+GMR\r\r\nAT version:1.1.0.0(May "
[2020-03-14T17:23:32Z TRACE atat::ingress_manager] Ingress: Switching to state ReceivingResponse
[2020-03-14T17:23:32Z TRACE atat::ingress_manager] Ingress: Receiving 32 bytes
[2020-03-14T17:23:32Z TRACE atat::ingress_manager] Ingress: Parsing / ReceivingResponse / "AT version:1.1.0.0(May 11 2016 18:09:56)\r\nSDK version:1"
[2020-03-14T17:23:32Z TRACE atat::ingress_manager] Ingress: Receiving 32 bytes
[2020-03-14T17:23:32Z TRACE atat::ingress_manager] Ingress: Parsing / ReceivingResponse / "AT version:1.1.0.0(May 11 2016 18:09:56)\r\nSDK version:1.5.4(baaeaebb)\r\ncompile time:May"
[2020-03-14T17:23:32Z TRACE atat::ingress_manager] Ingress: Receiving 23 bytes
[2020-03-14T17:23:32Z TRACE atat::ingress_manager] Ingress: Parsing / ReceivingResponse / "AT version:1.1.0.0(May 11 2016 18:09:56)\r\nSDK version:1.5.4(baaeaebb)\r\ncompile time:May 20 2016 15:08:19\r\nOK\r\n"
GetFirmwareVersion: parse("AT version:1.1.0.0(May 11 2016 18:09:56)\r\nSDK version:1.5.4(baaeaebb)\r\ncompile time:May 20 2016 15:08:19")
Result: Ok(FirmwareVersion("AT version:1.1.0.0(May 11 2016 18:09:56)\r\nSDK version:1.5.4(baaeaebb)\r\ncompile time:May 20 2016 15:08:19"))
[2020-03-14T17:23:32Z TRACE atat::ingress_manager] Ingress: Switching to state Idle
```

The `AT` response still doesn't work though:

```
Starting (dev=/dev/ttyUSB0, baud=115200)...
Sending command At
[2020-03-14T17:23:54Z DEBUG atat::client] Sending command: "AT\r\n"
[2020-03-14T17:23:54Z TRACE atat::ingress_manager] Ingress: Receiving 11 bytes
[2020-03-14T17:23:54Z TRACE atat::ingress_manager] Ingress: Parsing / Idle / "AT\r\r\n\r\nOK\r\n"
[2020-03-14T17:23:54Z TRACE atat::ingress_manager] Ingress: Switching to state ReceivingResponse
Result: Err(Timeout)
```

Any ideas?

**Comment by dbrgn** [comment]
Branch probably needs a rebase on top of master. Then, once the logging code is in here, you could change the `Parsing` string in the TRACE logs to `Digest` or `Digesting`.

**Comment by MathiasKoch** [comment]
Great!

On the AT one, i can't really replicate it in a unit test, i even tried here: https://github.com/BlackbirdHQ/atat/pull/25/files#diff-b2ca08eb90339c5362068c5615c87c04R249

can you maybe?

**Comment by dbrgn** [comment]
@MathiasKoch ah, the parsing works, I just needed to call `digest()` twice!

**Pull request merged**
