### PR TITLE
update embedded-io 0.6 and embassy-sync 0.3

### PR DESCRIPTION
**Pull request by tarfu**

### CODE REVIEW

**Review by MathiasKoch — APPROVED** [review]
Thank you!

**Comment by rmja** [comment]
@MathiasKoch Could we have a release with this change? 🚀

**Comment by MathiasKoch** [comment]
Absolutely! :rocket: 

Perhaps we should wait for this, if it yanks 0.6? https://github.com/rust-embedded/embedded-hal/pull/513

**Comment by rmja** [comment]
No need to wait, that issue will be a patch release according to the rust-embedded wg meeting today.

**Comment by MathiasKoch** [comment]
Awesome. 

I will release current master as 0.20.0

**Pull request merged**
