### PR TITLE
Parsing / Serialize Hex Array strings

### PR DESCRIPTION
**Pull request by mvniekerk**
Allows Hex array strings to be ser/de 'ed.

### CODE REVIEW

**Comment by MathiasKoch** [comment]
@mvniekerk I think with #142 merged, you should be able to rebase & restructure this PR in a way where we can merge it? 

Maybe put behind some nightly feature flag?

**Comment by mvniekerk** [comment]
Hi @MathiasKoch 
In my branch I also have @rmja 's URC code in (https://github.com/BlackbirdHQ/atat/pull/146).
So when that's merged in, then we can go wild.

**Comment by MathiasKoch** [comment]
@mvniekerk You should be able to rebase now :)

**Comment by mvniekerk** [comment]
Right Herr @MathiasKoch , it seems to be ready. Waiting for the build then.

**Comment by mvniekerk** [comment]
No longer marked as WIP. 
CC @MathiasKoch

**Comment by mvniekerk** [comment]
Hi @MathiasKoch , checking in on this again?

**Pull request merged**
